name: NetworkSlotsShield
version: 1.0
main: com.yours4nty.networkslotsshield.NetworkSlotsShield
author: YourS4nty
softdepend: [ProtocolLib]
api-version: 1.20
commands:
  networkshield:
    description: Toggle or debug the slot protection system
    usage: /networkshield <true|false|debug true|false>
    permission: networkshield.toggle
permissions:
  networkshield.toggle:
    default: op
